### ISSUE TITLE
Getting this error on fresh install

### ISSUE THREAD

**Issue by ZekiJohn** [homanp/langchain-ui#76]
I'm getting this error after installing it and visit localhost:3000

![image](https://user-images.githubusercontent.com/45900838/231312828-9c14c16b-3c37-4978-87e7-d66434460068.png)

![image](https://user-images.githubusercontent.com/45900838/231312960-dda03d8f-f36d-4f73-ae0b-0bbf823f12ef.png)

**Comment by homanp** [comment]
Thanks for reporting! Will take a look ASAP.

**Comment by homanp** [comment]
@ZekiJohn I just cloned the project and I'm not seeing this issue. 

Have you added the required `.env` variables?

Could you give some more context?

**Comment by ZekiJohn** [comment]
I did not set .env variables, I didn't thought that would cause this problem, where can I get those variable, sorry I'm new to Next

**Comment by homanp** [comment]
> I did not set .env variables, I didn't thought that would cause this problem, where can I get those variable, sorry I'm new to Next

LangChain UI requires a database and auth provider. I suggest using supabase.com for db and I personally use GitHub OAuth. You also need to provide OpenAI access token.

**Comment by rmajidy** [comment]
@homanp Do you need the db connection to get past the authentication to view the homepage? 

I've added my `NEXT_PUBLIC_GITHUB_ID` &  `NEXT_PUBLIC_GITHUB_SECRET` however I think I'm putting the wrong Authorization callback URL. 

The connection just fails every time I try to logging in with github

**Comment by homanp** [comment]
@rmajidy yes you need the db connection. Easiest way is to setup a db with Supabase.com or similar.

**Comment by rmajidy** [comment]
@homanp thanks for the quick reply! What do put in the `Authorization callback URL` in github Oauth section?

**Comment by homanp** [comment]
> @homanp thanks for the quick reply! What do put in the `Authorization callback URL` in github Oauth section?

I use this locally:

<img width="558" alt="Screenshot 2023-04-23 at 22 05 04" src="https://user-images.githubusercontent.com/2464556/233862978-547875ab-9d5c-42dc-8608-7611edd3dddd.png">

**Comment by rmajidy** [comment]
@homanp Awesome, thank you so much man!
