### ISSUE TITLE
`react-markdown` doesn't render code blocks properly when streaming the response.

### ISSUE THREAD

**Issue by homanp** [homanp/langchain-ui#79]
**Describe the bug**
`react-markdown` doesn't render code blocks properly when streaming the response.

**To Reproduce**

1. Ask the GPT to write some code

**Expected behavior**
The code block renderer should apply.

**Screenshots**
<img width="928" alt="Screenshot 2023-04-13 at 18 51 46" src="https://user-images.githubusercontent.com/2464556/231830116-df2fd25e-7f92-44e9-9400-f99fbf8d4fa9.png">

**Comment by homanp** [comment]
This is due to line breaks missing in the stream.

**Comment by SergeWilfried** [comment]
Looking forward for the fix

**Comment by homanp** [comment]
Working on this as we speak. And then I'll add so you can chat with whatever data source you want.

**Comment by homanp** [comment]
@SergeWilfried https://github.com/homanp/langchain-ui/pull/81
