### ISSUE TITLE
:lady_beetle: 404 when trying to access settings

### ISSUE THREAD

**Issue by adriens** [homanp/langchain-ui#94]
**Describe the bug**

I get a `404` when trying to access settings

**To Reproduce**

1. Go to https://langchain-ui.vercel.app/app
2. Signin
3. Click on `Settings`
5. Get the `404`

![image](https://user-images.githubusercontent.com/5235127/235542986-76727a7a-5f6e-43f0-9f36-78f8dc6fd657.png)

**Screenshots**

![image](https://user-images.githubusercontent.com/5235127/235543025-3e27ef63-9dec-4264-a3bb-7a530d820b3f.png)

![image](https://user-images.githubusercontent.com/5235127/235543007-6b96b129-abfc-4ba1-8ae3-a72bbca4bc35.png)

**Comment by homanp** [comment]
@adriens yes, the settings page hasn't been implemented yet. It will be added in the near future (e.g next week). 

I'm currently working on bringing a stable "Chat with your Documents" functionality and after that settings will be added.

**Comment by adriens** [comment]
> I'm currently working on bringing a stable "Chat with your Documents" functionality and after that settings will be added.

AWEOME :star_struck:
